__keys="rootkey"
rootkey={object}
rootkey__keys="subkey array"
rootkey_subkey={object}
rootkey_subkey__keys="key child"
rootkey_subkey_key="value"
rootkey_subkey_child="value"
rootkey_array=[array]
rootkey_array__length=3
rootkey_array_0="a"
rootkey_array_1="b"
rootkey_array_2="c"
